apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monty-eoapi.fullname" . }}-docker-config
  namespace: {{ include "monty-eoapi.fullname" . }}
  labels:
    app: monty-eoapi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""