# This file is used to create global secrets in the kubernetes cluster
# that can be used by any component in the monty-eoapi application
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monty-eoapi.fullname" . }}-secrets
  namespace: {{ include "monty-eoapi.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.global.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}