# This file is used to create a service account for the application.
# The service account is used to define the permissions that the application has in the kubernetes cluster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monty-eoapi.serviceAccountName" . }}
  namespace: {{ include "monty-eoapi.fullname" . }}
  labels:
    {{- include "monty-eoapi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - name: {{ include "monty-eoapi.fullname" . }}-docker-config
{{- with .Values.serviceAccount.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
